name: OWASP Dependency-Check CLI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Download OWASP Dependency-Check
        run: |
          VERSION=$(curl -s https://jeremylong.github.io/DependencyCheck/current.txt)
          echo "Using Dependency-Check version $VERSION"
          curl -sL "https://github.com/jeremylong/DependencyCheck/releases/download/v$VERSION/dependency-check-$VERSION-release.zip" -o dependency-check.zip
          unzip dependency-check.zip -d dependency-check

      - name: Run OWASP Dependency-Check CLI
        run: |
          ./dependency-check/bin/dependency-check.sh \
            --format HTML \
            --project "Feedback Producer" \
            --out dependency-check-report \
            --scan .

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report/dependency-check-report.htm
