name: OWASP Dependency-Check (CLI)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependency-Check CLI
        run: |
          curl -sLO https://github.com/dependency-check/dependency-check/releases/download/v12.1.1/dependency-check-12.1.1-release.zip
          unzip dependency-check-12.1.1-release.zip -d dependency-check

      - name: Run Dependency-Check CLI
        run: |
          ./dependency-check/bin/dependency-check.sh --format HTML --project "Producer Service" --scan . --out reports/

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports/dependency-check-report.html
