name: SpotBugs Static Analysis

on: [push, pull_request]

jobs:
  spotbugs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build project (skip tests)
        run: mvn -B clean package -DskipTests

      - name: Run SpotBugs (create HTML + XML)
        run: |
          mvn -B spotbugs:spotbugs \
              -Dspotbugs.htmlOutput=true \
              -Dspotbugs.xmlOutput=true \
              -Dspotbugs.failOnError=false

      - name: Upload SpotBugs reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-report
          path: |
            target/spotbugs.html
            target/spotbugsXml.xml
